### ISSUE TITLE
Permisson error

### ISSUE THREAD

**Issue by kroese** [lncm/docker-tor#28]
When using the latest image (0.4.7.13) I get a permission error during startup:

```
[warn] Error creating directory /data/.tor: Permission denied
[warn] Failed to parse/validate config: Couldn't create private data directory "/data/.tor"
```

When switching back to an older image (0.4.7.9) everything works again. I really don't understand why the latest build tries to look in `/data/.tor:` when the mounted volumes are in `/etc/tor` and `/var/lib/tor`.

**Comment by nolim1t** [comment]
Make sure you set the UID arg to your uid and make /data to a local directory that you have access too (such as your home directory).

This is confirmed to be working as it is used by runcitadel node
